# backend/app/services/reporting/page1/layout.py
from __future__ import annotations

from io import BytesIO
from typing import Dict, List

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.pdfbase.pdfmetrics import stringWidth

from .allocator import build_capital_allocation_lens


def _draw_footer(canvas, doc, signature: str) -> None:
    canvas.saveState()

    page_w, _ = doc.pagesize
    left_x = doc.leftMargin
    right_x = page_w - doc.rightMargin

    y = 0.55 * inch

    canvas.setStrokeColor(colors.HexColor("#E5E7EB"))
    canvas.setLineWidth(1)
    canvas.line(left_x, y + 10, right_x, y + 10)

    canvas.setFillColor(colors.HexColor("#6B7280"))
    canvas.setFont("Helvetica", 8)
    canvas.drawString(
        left_x,
        y,
        "Generated by Quant Research Critic · Deterministic output derived solely from the supplied analysis payload.",
    )

    sig = (signature or "").strip()
    if sig:
        max_chars = 96
        if len(sig) > max_chars:
            sig = sig[: max_chars - 1] + "…"
        canvas.drawString(left_x, y - 12, f"Signature: {sig}")

    page_label = f"Page {doc.page}"
    w = stringWidth(page_label, "Helvetica", 8)
    canvas.drawString(right_x - w, y - 12, page_label)

    canvas.restoreState()


def _build_metric_table(metrics: List[Dict[str, str]]) -> Table:
    rows = [[m.get("label", ""), m.get("value", "")] for m in (metrics or [])]
    if not rows:
        rows = [["—", "—"]]

    t = Table(rows, colWidths=[2.5 * inch, 2.0 * inch], hAlign="LEFT")
    t.setStyle(
        TableStyle(
            [
                ("FONT", (0, 0), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    return t


def _build_flag_table(flags: List[Dict[str, str]]) -> Table:
    rows = [["Flag", "Severity"]] + [
        [f.get("flag", ""), f.get("severity", "")] for f in (flags or [])
    ]
    t = Table(rows, colWidths=[4.0 * inch, 1.0 * inch], hAlign="LEFT")
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke),
                ("FONT", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("ALIGN", (-1, 1), (-1, -1), "CENTER"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    return t


def build_page1_pdf(
    payload: Dict,
    verdict: Dict,
    metrics: List[Dict[str, str]],
    flags: List[Dict[str, str]],
    signature: str,
    template: str = "summary",
) -> bytes:
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=LETTER,
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=72,
    )

    styles = getSampleStyleSheet()

    if "HeaderSmall" not in styles:
        styles.add(
            ParagraphStyle(
                name="HeaderSmall",
                fontSize=9,
                textColor=colors.grey,
                spaceAfter=4,
                tracking=0.5,
            )
        )
    if "VerdictGrade" not in styles:
        styles.add(
            ParagraphStyle(
                name="VerdictGrade",
                fontSize=36,
                leading=40,
                spaceAfter=4,
            )
        )
    if "VerdictDecision" not in styles:
        styles.add(
            ParagraphStyle(
                name="VerdictDecision",
                fontSize=12,
                leading=14,
                spaceAfter=4,
            )
        )
    if "VerdictSentence" not in styles:
        styles.add(
            ParagraphStyle(
                name="VerdictSentence",
                fontSize=11,
                leading=14,
                spaceAfter=12,
            )
        )
    if "SectionTitle" not in styles:
        styles.add(
            ParagraphStyle(
                name="SectionTitle",
                fontSize=12,
                leading=14,
                spaceBefore=12,
                spaceAfter=6,
            )
        )
    if "BodySmall" not in styles:
        styles.add(
            ParagraphStyle(
                name="BodySmall",
                fontSize=10,
                leading=13,
                textColor=colors.HexColor("#111827"),
                spaceAfter=6,
            )
        )
    if "Bullet" not in styles:
        styles.add(
            ParagraphStyle(
                name="Bullet",
                fontSize=10,
                leading=13,
                leftIndent=12,
                bulletIndent=0,
                spaceAfter=2,
            )
        )

    template = (template or "summary").strip().lower()
    if template not in {"summary", "risk_heavy", "allocator"}:
        template = "summary"

    elements: List = []

    # Header
    elements.append(Paragraph("QUANT RESEARCH CRITIC", styles["HeaderSmall"]))
    scoring_v = payload.get("scoring_version", "")
    schema_v = payload.get("schema_version", "")
    meta_right = f"Analysis v{scoring_v} · Schema v{schema_v}".strip(" ·")
    if meta_right:
        elements.append(Paragraph(meta_right, styles["HeaderSmall"]))
    elements.append(Spacer(1, 0.2 * inch))

    # Verdict
    elements.append(Paragraph(str(verdict.get("grade", "")), styles["VerdictGrade"]))
    elements.append(Paragraph(f"<b>{verdict.get('decision','')}</b>", styles["VerdictDecision"]))
    elements.append(Paragraph(str(verdict.get("sentence", "")), styles["VerdictSentence"]))

    metric_table = _build_metric_table(metrics)
    flag_table = _build_flag_table(flags) if flags else None

    # Modes
    if template == "risk_heavy":
        elements.append(Paragraph("Risk Snapshot", styles["SectionTitle"]))
        elements.append(flag_table if flag_table else Paragraph("No material red flags detected.", styles["Normal"]))
        elements.append(Paragraph("Key Numbers", styles["SectionTitle"]))
        elements.append(metric_table)

    elif template == "allocator":
        elements.append(Paragraph("Key Numbers", styles["SectionTitle"]))
        elements.append(metric_table)

        elements.append(Paragraph("Capital Allocation Lens", styles["SectionTitle"]))
        lens = build_capital_allocation_lens(payload, metrics, flags)

        roles = lens.get("roles") or []
        roles_text = ", ".join([str(r) for r in roles]) if roles else "Unclassified (insufficient signals)"
        band = str(lens.get("allocation_band", "")).strip()
        warnings = lens.get("warnings") or []
        inputs_line = str(lens.get("inputs_line", "")).strip()

        elements.append(Paragraph("<b>1) Portfolio Role Classification</b>", styles["BodySmall"]))
        elements.append(Paragraph(f"Tags: {roles_text}", styles["BodySmall"]))

        elements.append(Paragraph("<b>2) Risk Budget Impact</b>", styles["BodySmall"]))
        if band:
            elements.append(Paragraph(f"Suggested Max Allocation Band: <b>{band}</b>", styles["BodySmall"]))
        if inputs_line:
            elements.append(Paragraph(f"Inputs: {inputs_line}", styles["BodySmall"]))

        elements.append(Paragraph("<b>3) Stability Warning Layer</b>", styles["BodySmall"]))
        if warnings:
            for w in warnings:
                elements.append(Paragraph(str(w), styles["Bullet"], bulletText="•"))
        else:
            elements.append(Paragraph("No critical stability warnings triggered by current heuristics.", styles["BodySmall"]))

        elements.append(Paragraph("Risk Snapshot", styles["SectionTitle"]))
        elements.append(flag_table if flag_table else Paragraph("No material red flags detected.", styles["Normal"]))

    else:
        elements.append(Paragraph("Key Numbers", styles["SectionTitle"]))
        elements.append(metric_table)
        elements.append(Paragraph("Risk Snapshot", styles["SectionTitle"]))
        elements.append(flag_table if flag_table else Paragraph("No material red flags detected.", styles["Normal"]))

    doc.build(
        elements,
        onFirstPage=lambda c, d: _draw_footer(c, d, signature),
        onLaterPages=lambda c, d: _draw_footer(c, d, signature),
    )

    return buffer.getvalue()
